#!/bin/bash
# Generate Caddyfile from routes.json
# Reads $DEVPROXY_HOME (default: ~/.devproxy)
# Usage: caddy-generate.sh

set -e

DEVPROXY_HOME="${DEVPROXY_HOME:-$HOME/.devproxy}"
ROUTES_FILE="$DEVPROXY_HOME/config/routes.json"
CADDYFILE="$DEVPROXY_HOME/Caddyfile"

if [[ ! -f "$ROUTES_FILE" ]]; then
    echo "ERROR: $ROUTES_FILE not found" >&2
    exit 1
fi

python3 -c "
import json

with open('$ROUTES_FILE') as f:
    data = json.load(f)

lines = []
lines.append('{')
lines.append('    # Auto-generated by codelabs-dev-servers from routes.json')
lines.append('    # DO NOT EDIT - changes will be overwritten')
lines.append('    local_certs')
lines.append('    admin localhost:2019')
lines.append('    log {')
lines.append('        level WARN')
lines.append('    }')
lines.append('}')
lines.append('')

# Group routes by project
projects = {}
for r in data.get('routes', []):
    if not r.get('enabled', True):
        continue
    proj = r.get('project', 'unknown')
    projects.setdefault(proj, []).append(r)

for proj in sorted(projects.keys()):
    lines.append(f'# === {proj} ===')
    lines.append('')
    for r in projects[proj]:
        domain = r['domain']
        upstream = r['upstream']
        extra = r.get('extra_routes', [])

        if extra:
            lines.append(f'{domain} {{')
            for er in extra:
                lines.append(f'    handle {er[\"path\"]} {{')
                lines.append(f'        reverse_proxy {er[\"upstream\"]}')
                lines.append('    }')
            lines.append('    handle {')
            lines.append(f'        reverse_proxy {upstream}')
            lines.append('    }')
            lines.append('}')
        else:
            lines.append(f'{domain} {{')
            lines.append(f'    reverse_proxy {upstream}')
            lines.append('}')
        lines.append('')

if not projects:
    lines.append('# No routes configured. Use caddy-add-route.sh to add one.')

print('\n'.join(lines))
" > "$CADDYFILE"

ROUTE_COUNT=$(python3 -c "import json; print(len([r for r in json.load(open('$ROUTES_FILE')).get('routes',[]) if r.get('enabled',True)]))")
echo "CADDYFILE_GENERATED=$CADDYFILE"
echo "ROUTE_COUNT=$ROUTE_COUNT"
